###### Nama: Hafizh M Rasyid

# Exercise 4

1. Create a null vector / 1D array of size 10 and update fifth value to 11.

In [4]:
import numpy as np

In [21]:
array1 = np.zeros(10, dtype = int)
array1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
array1[4] = 11
array1

array([ 0,  0,  0,  0, 11,  0,  0,  0,  0,  0])

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [12]:
array2 = np.arange(6).reshape(2, 3)
array2

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
array2.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [33]:
array3 = np.ones((5, 5), dtype = int)
array3[1, 1:4] = 0
array3[2, 1:4] = 0
array3[3, 1:4] = 0

array3

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

4. Take a look at the following matrix. Access the [2, 1,1]

In [35]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [39]:
z1= z[2, 0]
z1[::-1]

array([2, 1, 1])

# Assignment

1. Create a 4x4 matrix with values ranging from 0 to 3.

In [50]:
array4 = np.zeros((4, 4), dtype = int)
array4 += np.arange(4)

array4

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [55]:
array5 = np.arange(16, dtype = int).reshape(4, 4)

array5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.hsplit(array5, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]